
sudo: required

services:
  - docker

env:
  matrix:
    - TRAVIS_DEBIAN_DISTRIBUTION=wheezy DPUT=1

before_install:
  - set -e
  - sudo apt-get -qq --yes install devscripts dpkg-dev
  - dch -b --newversion `git describe|sed -E 's#.*/##'|sed -E 's/-([0-9]+)-(.{8})$/+\1.\2/'`~$TRAVIS_DEBIAN_DISTRIBUTION --force-distribution --distribution nowtaxi 'Autobuilt by git commit' 
  - git commit -m 'update changelog' debian/changelog
  - dpkg-parsechangelog

script:
  - set -e
  - wget -O- http://travis.debian.net/script.sh | sh -
  
  - echo $UPLOAD_SSH_KEY | base64 -d > ../issh
  - chmod 0600 ../issh

  - echo '[nowtaxi]' > ../dput.cf
  - echo login = gitlabuploader >> ../dput.cf
  - echo fqdn = debian.nowtaxi.ru >> ../dput.cf
  - echo method = scp >> ../dput.cf
  - echo incoming = /srv/debian.incomming/ >> ../dput.cf
  - echo ssh_config_options = UserKnownHostsFile=/dev/null >> ../dput.cf
  - echo '     StrictHostKeyChecking=no' >> ../dput.cf
  - echo '     IdentityFile=../issh'  >> ../dput.cf

  - if test "$DPUT" -eq 1; then dput --debug -u -c ../dput.cf nowtaxi ../*.changes; fi
  
  - cat ../*.changes

branches:
  only:
    - master
